name: Continuos Integrations

on:
  pull_request:
    branches: ['develop']

jobs:

  dockerHub:

    runs-on: ubuntu-latest

    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build Application JAR
        working-directory: .
        run: mvn clean package -DskipTests

      - name: Docker Compose Build
        working-directory: .
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest